Documentsをスマホとタブレットに対応
ReoYabiku/aloha-hp-next pull request #15
Opened 2023-09-07 09:26 UTC by tsunekazuomija

documentsをスマホとタブレットに対応させました。
- タブレット場合の「閲覧はこちら」と「ダウンロードはこちら」が左に寄りすぎな気がしますが、文章の量が増えると違和感がなくなるかもと思い、放置しています。

2023-09-08 10:59 UTC, ReoYabiku requested changes
@tsunekazuomija 
レスポンシブ対応ありがとうございます！
要素の配置については完璧だと思います！

`iframe`タグで切り抜いているPDFファイルについて、ブラウザの検証画面ではなくスマホで確認するとPDFがずれてしまうので、これがPCと同様になるように修正することって可能ですか？

| 理想 | 現状 |
| --- | --- |
| PCのブラウザで、検証モードを用いて再現 | プレビュー用のURLを実際にスマホで開いて再現 |
| <img width="1440" alt="スクリーンショット 2023-09-08 19 55 01" src="https://github.com/ReoYabiku/aloha-hp-next/assets/99821810/a51858b7-359a-4ac4-89d2-e4a590697951"> | ![IMG_71BFDA979FD7-1](https://github.com/ReoYabiku/aloha-hp-next/assets/99821810/43ad4c90-b455-4b54-8a06-5dc48f023687) |

Vercelに自分しか入れない都合で、プレビューリンクにアクセスできなかったら教えてください！

2023-09-08 11:01 UTC, ReoYabiku commented
@tsunekazuomija 
以前9/8までにHPを一段落させたいと伝えましたが、今回は自分のレビューが遅くなってしまったので修正が遅くなっても問題ありません！申し訳ないです！

2023-09-09 02:25 UTC, tsunekazuomija commented
修正してみましたが、僕の手元だと

<img src="https://github.com/ReoYabiku/aloha-hp-next/assets/107994009/6372b637-a256-4a2e-82a2-e1972757f653" width="320px">

になってしまい、確認できないです😢
google pixelのchromeとgoogleで確認しました。

2023-09-09 05:30 UTC, tsunekazuomija commented
ipadでリンクを開くことで問題が確認できたのですが、色々変更してもうまくいかず、結局[documentsをタブレット端末に対応](https://github.com/ReoYabiku/aloha-hp-next/pull/15/commits/0e495f27a48187ef24fc5da71fc99e38311286a9)のコミットまで戻しました。

2023-09-09 05:37 UTC, tsunekazuomija commented
ついでに、検証画面をpcのサファリで開くと
<img width="1440" alt="スクリーンショット 2023-09-09 14 35 59" src="https://github.com/ReoYabiku/aloha-hp-next/assets/107994009/cfe32437-ec9d-4679-a01f-adafc7c10485">
のようにツールバーが表示されてしまうことがわかったのですが、これの解決方法もわかりませんでした

2023-09-10 06:40 UTC, ReoYabiku approved these changes
@tsunekazuomija 
調査ありがとうございます！
サファリのバグも見つかってよかったです！今回はこれでマージしましょう！

今回治せなかった項目について、イシューに起票していてくれると助かります！

![LGTM](https://images.lgtmgen.org/e63d48f6-778a-4e48-8070-7cd30a09bb50)

2023-09-11 04:06 UTC, merged