membersをprismaに対応
ReoYabiku/aloha-hp-next pull request #20
Opened 2023-09-16 06:35 UTC by tsunekazuomija

membersをデータベースから取得するようにしました。
- `{leader && (<...>)}`を入れないと怒られるので入れています。

<img width="549" alt="スクリーンショット 2023-09-16 15 32 43" src="https://github.com/ReoYabiku/aloha-hp-next/assets/107994009/8de6b716-e737-40a7-8b0a-11e1f031391f">

- ガンダムは目立つのでやめたほうがよい

2023-09-16 07:58 UTC, ReoYabiku requested changes
@tsunekazuomija 
データベースとの接続ありがとうございます！
一点コメントしたので修正をお願いします！

2023-09-16 07:58 UTC, ReoYabiku commented on app/members/page.tsx
> +      {leader && (
波括弧で囲う範囲をpersonだけにして欲しいです！
万が一leaderを取得できなかったとしても挨拶文は残したいので！

2023-09-16 08:01 UTC, ReoYabiku commented
本当は自分もアイコンにしたかったんですが、大見謝くんの他に誰もアイコンの人がいなくて衝撃でした……！笑

せっかくなので、次のミーティングまでに実写の写真を用意しておいてください。
せっかくなので一緒にAWSに登録しましょう！

2023-09-18 11:02 UTC, tsunekazuomija commented on app/members/page.tsx
> +      {leader && (
修正しました！

2023-09-18 11:03 UTC, tsunekazuomija commented
写真探しておきます！

2023-09-18 11:04 UTC, ReoYabiku approved these changes
@tsunekazuomija 
修正ありがとうございます！よくできているとおもいます！

![LGTM](https://images.lgtmgen.org/ba3bf4ea-44e6-4b06-97aa-d2d5c5f959d3)

2023-09-18 11:06 UTC, ReoYabiku commented
一度レビューをした後であっても、修正が完了したら再度レビューのリクエストをしてほしいです！！

形式的なことで申し訳ないのですが、してくれると分かり易いので！

2023-09-18 14:08 UTC, tsunekazuomija commented
承知しました！

2023-09-18 14:08 UTC, merged